version: 2
jobs:
  build:
    machine: true
    branches:
      - release-v1.9.8
    steps:
      - checkout
      # build the Docker image (this will use the Dockerfile in the root of the repo)
      - run: 
          name: BUILD IMAGE
          command: |
            IMAGE_NAME="jonascavalcantineto/kube-apiserver:1.9.8"
            docker build -t $IMAGE_NAME .
      # authenticate with the Docker Hub registry
      - run: 
          name: LOGIN DOCKER HUB
          command: docker login --username jonascavalcantineto --password j7b9c1n1
      # push the new Docker image to the Docker registry
      - run: 
          name: PUSH IMAGE
          command: docker push $IMAGE_NAME
        